### ISSUE TITLE
Usability - Exploitation Types List Screen - Screen Switching Problem

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#19]
When attempting to scroll through the list of items for an individual country if you happen to use one finger on a country that doesn’t have many exploitation types the screen switches to the next type listed at the top of the page. With the iOS version of the application, a person needs to tap the type at the top of the screen that you can do for Android too.

**Comment by aquilent-dgemoets** [comment]
By default in Android, a swipe gesture will navigate to the next tab in a tabbed screen like this one.  However, because some countries' rows will themselves be horizontally scrollable, it seems reasonable to disable the swipe-changes-tabs behavior (we've seen cases where developers have wanted to do the same thing).  We will fix this for release, hopefully by the next beta.  Good catch.

**Comment by jfc3-dol** [comment]
Thanks, for correcting this issue and I will close it.
