### ISSUE TITLE
Accessibility - Individual Goods Screen - Talkback Does Not Tell User Country is a button or Link 

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#46]
Why are the types of goods not buttons so someone using TalkBack would know to tap them to get more detail about the exploited goods

**Comment by aquilent-dgemoets** [comment]
See discussion for #35.

**Comment by jfc3-dol** [comment]
It would be best to add that a button or link is tap-able or clickable to TalkBack users know there is more data/information on another screen similar to what was done on the home screen for ILAB and DOL websites at the bottom of the screen.

**Comment by aquilent-dgemoets** [comment]
Agreed-- we actually looked into it last night but it was non-trivial to fix due to the compound nature of the Country list item (flag icon plus country name plus 1-3 exploitation types).  We still hope to address this in the final release.

**Comment by aquilent-dgemoets** [comment]
This is addressed in the latest beta (uploaded Friday 12/4).

**Comment by nmangu** [comment]
Latest BETA-5 Release: TalkBack is announcing 'Countries' as button. Verified and validated as working.

**Comment by aquilent-dgemoets** [comment]
Great. Are you authorized to close issues, or are there other open aspects to this issue?

**Comment by nmangu** [comment]
Yes, we are authorized to close issues that are fixed. However, since these were opened by the Sr. Accessibility Specialist, he might want to review these once he would be back on Tuesday. You may go ahead and consider these (the ones that are fixed, re-tested and passed) as closed. Please be aware that the ones that were beyond the scope of the fix would still be considered as 'open' till our Sr. Accessibility Specialist reviewed and closed them himself.

**Comment by jfc3-dol** [comment]
TalkBack was able to read all the exploited goods I checked as a button and that you can double tap to activate them.
