### ISSUE TITLE
Accessibility - Exploitation Types Screen - TalkBack Does Not Notify User Good is Button/Link

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#51]
TalkBack does not inform the user that a good can be tapped because it’s either a button or link to more content.

**Comment by aquilent-dgemoets** [comment]
See discussion for #35.

**Comment by jfc3-dol** [comment]
It would be best to add that a button or link is tap-able or clickable to TalkBack users know there is more data/information on another screen similar to what was done on the home screen for ILAB and DOL websites at the bottom of the screen.

**Comment by aquilent-dgemoets** [comment]
Agreed--we still hope to address this in the final release.

**Comment by aquilent-dgemoets** [comment]
This is addressed in the latest beta (uploaded Friday 12/4).

**Comment by nmangu** [comment]
Latest BETA-5 update: TalkBack does notify user that 'Goods' is a Button. Verified and validated as working.

**Comment by aquilent-dgemoets** [comment]
Great. Are you authorized to close issues, or are there other open aspects to this issue?

**Comment by nmangu** [comment]
Yes, we are authorized to close issues that are fixed. However, since these were opened by the Sr. Accessibility Specialist, he might want to review these once he would be back on Tuesday. You may go ahead and consider these (the ones that are fixed, re-tested and passed) as closed. Please be aware that the ones that were beyond the scope of the fix would still be considered as 'open' till our Sr. Accessibility Specialist reviewed and closed them himself.

**Comment by jfc3-dol** [comment]
TalkBack was able to read all the exploited goods I checked as a button and that you can double tap to activate them.
