### ISSUE TITLE
Fucntional - More Info - Not Able to Open PDFs

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Child-Labor-Android#79]
While looking at the "More Info" screen to check if the PDFs were blurry or not, I noticed that the following PDF links are not available and pointing to versions from 2016 and 2014. 

NOTE: Add year to end of link name,

- Child Labor Report
- Child and Forced Labor List of Goods (2016)
- Forced Child Labor List of Product (2014)

**Comment by clguidi** [comment]
Thanks John! We do not yet have the PDF URL for the newest Child Labor Report so that will not be addressed until later. I will provide the Child and Forced Labor List of Goods (2018) as that is the most recent one. Forced Child Labor List of Products (2014) is the most recent and will not be changing. 

I cannot request that we add the year to end of link name as that is outside the purview of the app developers.

**Comment by jfc3-dol** [comment]
@clguidi,

Okay, I'm looking forward to the updates.

**Comment by clguidi** [comment]
John, this has been addressed. Please download the latest build and close the issue when possible.

**Comment by jfc3-dol** [comment]
@clguidi,

I'm now able to open the PDFs found on the "More Info" screen, so I'm going to close this issue.
